server:
  port: 9092
  
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    
security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: .LogicBiz@#019283
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        #data: classpath:/sql/data.sql
        #driver-class-name: com.mysql.cj.jdbc.Driver
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        password: 'Trixrio@'
        #platform: mysql
        #schema: classpath:/sql/schema.sql
        #url: jdbc:mysql://localhost/oauth?useTimezone=true&serverTimezone=UTC
        url: jdbc:sqlserver://localhost;databaseName=pendotiba_logic_bus
        username: sa
    jpa:
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database-platform: org.hibernate.dialect.SQLServer2008Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    profiles:
        active: oauth-security
     
logging:
    file: /logs/server-oauth.log